=== Jhonathan-Pizarra/XML-DTD/DTD-XML/src/java/desafio/AgendaDTD.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--Validación a nivel de elementos-->
<!ELEMENT agenda  (contacto)*> <!--agenda es el elemento raíz y luego tiene una serie de hijos-->

<!-- Validaciones a nivel de atributos-->
<!ELEMENT contacto (nombre, apellido+, telefono, email?, direccion)> 

<!ELEMENT nombre (#PCDATA)> 
<!ELEMENT apellido (#PCDATA)> 
<!ELEMENT telefono (#PCDATA)> 
<!ELEMENT email (#PCDATA)>

<!ELEMENT direccion (calle, numero, cp)>
<!ELEMENT calle (#PCDATA)> 
<!ELEMENT numero (#PCDATA)> 
<!ELEMENT cp (#PCDATA)> 

<!ATTLIST telefono pais CDATA #REQUIRED>

=== Jhonathan-Pizarra/XML-DTD/DTD-XML/src/java/desafio/Agenda.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE agenda SYSTEM 'AgendaDTD.dtd'> <!--Referenciamos-->

<agenda>
    <contacto>
        <nombre>Jhonathan</nombre>
        <apellido>Pizarra</apellido>
        <telefono pais="EC">0990803129</telefono>
        <email>jhonnathan.pizarra@epn.edu.ec</email>
        <direccion>
            <calle>Solanda</calle>
            <numero>26</numero>
            <cp>173101</cp>
        </direccion>
    </contacto>
    
    <contacto>
        <nombre>Erick</nombre>
        <apellido>Bola√±os</apellido>
        <apellido>Guerrero</apellido>
        <telefono pais="JAP">0998754865</telefono>
        <!--Email puede o no haber-->
        <direccion>
            <calle>San Bartolo</calle>
            <numero>23</numero>
            <cp>156023</cp>
        </direccion>
    </contacto>
 
</agenda>
